### ISSUE TITLE
a group of order 104 with 14 conjugacy classes is missing

### ISSUE THREAD

**Issue by ThomasBreuer** [stertooy/SmallClassNr#7]
You list only one group of order 104 with 14 conjugacy classes.
GAP's `AllSmallGroups( Size, 104, NrConjugacyClasses, 14 )` yields two groups.

As soon as the missing group gets added, the list from this package agrees with the cited paper on the groups with 13 or 14 conjugacy classes in the sense that both describe 93 groups with 14 conjugacy classes.

**Comment by stertooy** [comment]
Thank you for the report!

No idea how I managed to miss that particular group. In any case, I'll release a new version with the missing group added soon.
